/**
 * Postgres schema for one Understanding Graph project.
 *
 * One Postgres *schema* per project, mirroring the one-store.db-per-project
 * layout of the SQLite backend. Design rules, and why:
 *
 *  - Timestamps stay TEXT in 'YYYY-MM-DD HH:MM:SS' UTC form. The engine sorts,
 *    slices and string-compares these values in dozens of places
 *    (getEventLog, getRecentCommits, lock expiry, decay scoring). Promoting
 *    them to timestamptz would change every one of those comparisons; keeping
 *    TEXT keeps the port behaviour-preserving.
 *
 *  - Booleans stay INTEGER. The SQL says `active = 1` and `validated = 0`
 *    throughout; a real boolean column would reject those comparisons.
 *
 *  - No FOREIGN KEY constraints. The SQLite backend never enables
 *    `PRAGMA foreign_keys`, so its FK clauses are inert documentation and the
 *    live corpus contains rows that would violate them (nodes carry
 *    tool_call_id values with an empty tool_calls table). Declaring real FKs
 *    here would reject writes SQLite has always accepted.
 *
 *  - Full-text search replaces the FTS5 virtual table and its three sync
 *    triggers with a GIN expression index over title+understanding. An
 *    expression index rather than a stored tsvector column, because the engine
 *    reads nodes with SELECT * and would otherwise pull a tsvector along on
 *    every read.
 *
 *  - nodes.embedding is pgvector `vector(dim)`, dim from UG_EMBEDDING_DIM.
 */

import { getEmbeddingDimension } from '../../services/EmbeddingService.js';

/** Tables in dependency-free creation order. */
export const TABLES = [
  'conversations',
  'documents',
  'commits',
  'tool_calls',
  'nodes',
  'edges',
  'chat_history',
  'project_meta',
  'event_log',
  'solvers',
  'tasks',
  'solver_feedback',
  'enforcement_log',
  'resource_locks',
  'text_sources',
] as const;

const NOW = "to_char((now() at time zone 'UTC'), 'YYYY-MM-DD HH24:MI:SS')";

/**
 * Full DDL for a project schema. Idempotent: safe to run on every startup,
 * which is how the SQLite backend behaves too.
 */
export function projectSchemaDdl(schema: string, embeddingDim: number): string {
  return `

CREATE TABLE IF NOT EXISTS conversations (
  id              TEXT PRIMARY KEY,
  query           TEXT NOT NULL,
  response        TEXT,
  created_at      TEXT DEFAULT ${NOW},
  metadata        TEXT
);

CREATE TABLE IF NOT EXISTS documents (
  hash            TEXT PRIMARY KEY,
  original_name   TEXT NOT NULL,
  mime_type       TEXT,
  size_bytes      INTEGER,
  uploaded_at     TEXT DEFAULT ${NOW},
  conversation_id TEXT
);
CREATE INDEX IF NOT EXISTS idx_documents_name ON documents(original_name);

CREATE TABLE IF NOT EXISTS commits (
  id              TEXT PRIMARY KEY,
  message         TEXT NOT NULL,
  agent_name      TEXT,
  author          TEXT,
  node_ids        TEXT DEFAULT '[]',
  edge_ids        TEXT DEFAULT '[]',
  created_at      TEXT DEFAULT ${NOW}
);
CREATE INDEX IF NOT EXISTS idx_commits_created ON commits(created_at);

CREATE TABLE IF NOT EXISTS tool_calls (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id      TEXT NOT NULL,
  tool_name       TEXT NOT NULL,
  arguments       TEXT,
  result          TEXT,
  error           TEXT,
  duration_ms     INTEGER,
  created_at      TEXT DEFAULT ${NOW}
);
CREATE INDEX IF NOT EXISTS idx_tool_calls_session ON tool_calls(session_id);
CREATE INDEX IF NOT EXISTS idx_tool_calls_tool ON tool_calls(tool_name);

CREATE TABLE IF NOT EXISTS nodes (
  id              TEXT PRIMARY KEY,
  title           TEXT NOT NULL,
  trigger         TEXT,
  why             TEXT,
  understanding   TEXT,
  source_elements TEXT,
  validated       INTEGER,
  active          INTEGER DEFAULT 1,
  version         INTEGER DEFAULT 1,
  revisions       TEXT DEFAULT '[]',
  conversation_id TEXT,
  created_at      TEXT DEFAULT ${NOW},
  updated_at      TEXT,
  archived_at     TEXT,
  archive_reason  TEXT,
  "references"    TEXT DEFAULT '[]',
  metadata        TEXT DEFAULT '{}',
  tool_call_id    INTEGER,
  embedding       vector(${embeddingDim}),
  last_accessed   TEXT,
  access_count    INTEGER DEFAULT 0,
  content         TEXT,
  summary         TEXT,
  level           TEXT,
  is_doc_root     INTEGER,
  file_type       TEXT,
  commit_id       TEXT
);
CREATE INDEX IF NOT EXISTS idx_nodes_active ON nodes(active);
CREATE INDEX IF NOT EXISTS idx_nodes_trigger ON nodes(trigger);
CREATE INDEX IF NOT EXISTS idx_nodes_conversation ON nodes(conversation_id);
CREATE INDEX IF NOT EXISTS idx_nodes_tool_call ON nodes(tool_call_id);
CREATE INDEX IF NOT EXISTS idx_nodes_commit ON nodes(commit_id);
CREATE INDEX IF NOT EXISTS idx_nodes_level ON nodes(level);
CREATE INDEX IF NOT EXISTS idx_nodes_doc_root ON nodes(is_doc_root);
-- Expression index rather than a stored tsvector column: the engine reads
-- nodes with SELECT *, and a stored tsvector would be shipped over the wire on
-- every one of those reads. The FTS query in dialect.ts spells this expression
-- out identically so the planner still uses this index.
CREATE INDEX IF NOT EXISTS idx_nodes_fts ON nodes USING GIN (
  to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(understanding, ''))
);

CREATE TABLE IF NOT EXISTS edges (
  id              TEXT PRIMARY KEY,
  from_id         TEXT NOT NULL,
  to_id           TEXT NOT NULL,
  type            TEXT DEFAULT 'relates',
  explanation     TEXT,
  why             TEXT,
  active          INTEGER DEFAULT 1,
  version         INTEGER DEFAULT 1,
  revisions       TEXT DEFAULT '[]',
  conversation_id TEXT,
  created_at      TEXT DEFAULT ${NOW},
  updated_at      TEXT,
  tool_call_id    INTEGER,
  commit_id       TEXT
);
CREATE INDEX IF NOT EXISTS idx_edges_from ON edges(from_id);
CREATE INDEX IF NOT EXISTS idx_edges_to ON edges(to_id);
CREATE INDEX IF NOT EXISTS idx_edges_type ON edges(type);
CREATE INDEX IF NOT EXISTS idx_edges_active ON edges(active);
CREATE INDEX IF NOT EXISTS idx_edges_tool_call ON edges(tool_call_id);
CREATE INDEX IF NOT EXISTS idx_edges_commit ON edges(commit_id);

CREATE TABLE IF NOT EXISTS chat_history (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor           TEXT,
  event           TEXT,
  content         TEXT,
  metadata        TEXT,
  timestamp       TEXT DEFAULT ${NOW}
);

CREATE TABLE IF NOT EXISTS project_meta (
  key             TEXT PRIMARY KEY,
  value           TEXT
);

CREATE TABLE IF NOT EXISTS event_log (
  seq             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp       TEXT DEFAULT ${NOW},
  action          TEXT NOT NULL,
  entity_type     TEXT NOT NULL,
  entity_id       TEXT NOT NULL,
  conversation_id TEXT,
  summary         TEXT,
  details         TEXT
);
CREATE INDEX IF NOT EXISTS idx_event_log_timestamp ON event_log(timestamp);
CREATE INDEX IF NOT EXISTS idx_event_log_entity ON event_log(entity_type, entity_id);

CREATE TABLE IF NOT EXISTS solvers (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL UNIQUE,
  role            TEXT NOT NULL,
  manifest        TEXT NOT NULL,
  created_at      TEXT DEFAULT ${NOW}
);
CREATE INDEX IF NOT EXISTS idx_solvers_name ON solvers(name);

CREATE TABLE IF NOT EXISTS tasks (
  id              TEXT PRIMARY KEY,
  solver_id       TEXT NOT NULL,
  input_payload   TEXT NOT NULL,
  output_payload  TEXT,
  status          TEXT DEFAULT 'pending',
  accept_spec     TEXT,
  parent_task_id  TEXT,
  depth           INTEGER DEFAULT 0,
  session_id      TEXT,
  created_at      TEXT DEFAULT ${NOW},
  updated_at      TEXT
);
CREATE INDEX IF NOT EXISTS idx_tasks_solver ON tasks(solver_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_parent ON tasks(parent_task_id);

CREATE TABLE IF NOT EXISTS solver_feedback (
  id              TEXT PRIMARY KEY,
  solver_id       TEXT NOT NULL,
  task_id         TEXT,
  feedback_type   TEXT NOT NULL,
  content         TEXT NOT NULL,
  failed_gate     TEXT,
  created_at      TEXT DEFAULT ${NOW}
);
CREATE INDEX IF NOT EXISTS idx_feedback_solver ON solver_feedback(solver_id);

CREATE TABLE IF NOT EXISTS enforcement_log (
  id              TEXT PRIMARY KEY,
  target_id       TEXT NOT NULL,
  light           TEXT NOT NULL,
  pure_json       TEXT NOT NULL,
  enforcer_id     TEXT,
  created_at      TEXT DEFAULT ${NOW}
);
CREATE INDEX IF NOT EXISTS idx_enforcement_target ON enforcement_log(target_id);
CREATE INDEX IF NOT EXISTS idx_enforcement_light ON enforcement_log(light);

CREATE TABLE IF NOT EXISTS resource_locks (
  id              TEXT PRIMARY KEY,
  resource_id     TEXT NOT NULL,
  resource_type   TEXT DEFAULT 'node',
  holder_id       TEXT NOT NULL,
  holder_type     TEXT DEFAULT 'session',
  lock_type       TEXT DEFAULT 'exclusive',
  scope           TEXT DEFAULT 'node',
  acquired_at     TEXT DEFAULT ${NOW},
  expires_at      TEXT NOT NULL,
  reason          TEXT,
  CONSTRAINT resource_locks_resource_holder_key UNIQUE (resource_id, holder_id)
);
CREATE INDEX IF NOT EXISTS idx_locks_resource ON resource_locks(resource_id);
CREATE INDEX IF NOT EXISTS idx_locks_holder ON resource_locks(holder_id);
CREATE INDEX IF NOT EXISTS idx_locks_expires ON resource_locks(expires_at);

CREATE TABLE IF NOT EXISTS text_sources (
  id                     TEXT PRIMARY KEY,
  title                  TEXT NOT NULL,
  source_type            TEXT,
  content                TEXT NOT NULL,
  position               INTEGER DEFAULT 0,
  total_length           INTEGER,
  project_id             TEXT,
  root_node_id           TEXT,
  last_committed_node_id TEXT,
  status                 TEXT DEFAULT 'pending',
  created_at             TEXT DEFAULT ${NOW},
  updated_at             TEXT
);
CREATE INDEX IF NOT EXISTS idx_text_sources_project ON text_sources(project_id);
CREATE INDEX IF NOT EXISTS idx_text_sources_status ON text_sources(status);
`;
}

/**
 * Statements that run once per connection, before any project DDL.
 * CREATE EXTENSION needs privileges the app user may not have on a managed
 * instance, hence the IF NOT EXISTS plus a tolerant caller.
 */
export const BOOTSTRAP_DDL =
  'CREATE EXTENSION IF NOT EXISTS vector SCHEMA public;';

/**
 * If the embedding dimension configured in the environment no longer matches
 * the deployed column, fix it — but only while the column holds no data.
 * Silently truncating or reinterpreting existing vectors would corrupt the
 * corpus, so a populated mismatch is an error the operator must resolve.
 */
export function embeddingDimFixupSql(schema: string, dim: number): string {
  return `
DO $ug$
DECLARE
  current_dim int;
  populated   bigint;
BEGIN
  SELECT a.atttypmod INTO current_dim
  FROM pg_attribute a
  JOIN pg_class c ON c.oid = a.attrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = '${schema}' AND c.relname = 'nodes' AND a.attname = 'embedding';

  IF current_dim IS NULL OR current_dim = ${dim} THEN
    RETURN;
  END IF;

  EXECUTE format('SELECT count(*) FROM %I.nodes WHERE embedding IS NOT NULL', '${schema}')
    INTO populated;

  IF populated > 0 THEN
    RAISE EXCEPTION 'UG_EMBEDDING_DIM is % but %.nodes.embedding is vector(%) holding % embeddings. Re-embed the corpus (graph_backfill_embeddings) or restore the previous UG_EMBEDDING_DIM; the backend will not reinterpret stored vectors.',
      ${dim}, '${schema}', current_dim, populated;
  END IF;

  EXECUTE format('ALTER TABLE %I.nodes ALTER COLUMN embedding TYPE vector(%s)', '${schema}', ${dim});
END
$ug$;
`;
}

/** Convenience: the dimension the running configuration expects. */
export function configuredEmbeddingDim(): number {
  return getEmbeddingDimension();
}
